- name: "Create Backend App Directory"
  file:
    path: /home/ubuntu/udapeople-backend
    state: directory

- name: "Unarchive backend artefact files"
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/udapeople-backend

- name: "Install Dependencies"
  shell: |
    cd /home/ubuntu/udapeople-backend
    npm install

- name: "Executing Backend Service with PM2"
  become: true
  shell: |
    cd /home/ubuntu/udapeople-backend/
    pm2 stop default
    pm2 start npm -- start
  register: udapeople_backend_server

- name: "Log Server Messages"
  debug:
    msg: "{{ udapeople_backend_server.stdout_lines }}"

- name: "Restart after reboot"
  shell: |
#     # sudo su -c "env PATH=$PATH:/home/unitech/.nvm/versions/node/v14.3/bin pm2 startup <distribution> -u <user> --hp <home-path>
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save --force